course_name = "能动电气类跨专业课程"
course_code = "Cross-ENER"
repo_type = "multi-project"
description = "本仓库包含机器人与先进制造学院开设的能源动力类和电气类跨专业课程。"

[[courses]]
name = "氢能与燃料电池"

[[courses.teachers]]
name = "王夷飞"

[[courses.teachers.reviews]]
content = "王夷飞老师非常好，允许不去上课，考勤给满分，考核要求是写一篇小论文，给分也很高。"
author = { name = "海边的星空", link = "", date = "2025-01" }

[[courses.sections]]
title = "考查方式更新"

[[courses.sections.items]]
content = "25秋，该课程的课程大纲中增添了闭卷考试，但在实际上课时，仍然遵循无考试，只写一篇小论文的考察方式。"
author = { name = "jiazero", link = "https://github.com/jiazero", date = "2025-12" }

[[courses]]
name = "智慧低碳能源发电技术导论"

[[courses.teachers]]
name = "潘泽华"

[[courses.teachers.reviews]]
content = """
潘泽华老师总共考勤两次，上课很简单。老师极善良的。
考试开卷，可以把上课 PPT 全部打印出来现场找答案，很轻松能拿到接近满分的成绩。
"""
author = { name = "Caesia-ma", link = "https://github.com/Caesia-ma/", date = "2025-01" }

[[courses.sections]]
title = "考勤与Pre (25秋)"

[[courses.sections.items]]
content = """
25 秋共考勤三次，分别为第一节课，汇报那节课和最后一节课。
增加了一个小组 pre，要求三分钟内讲完，之后小组成员现场回答一个问题，问题很简单，不用担心
"""
author = { name = "Cecilia", link = "https://github.com/mircecilia/", date = "2026-01" }

[[courses]]
name = "核能与安全"

[[courses.teachers]]
name = "鞠鹏"

[[courses.teachers.reviews]]
content = """
主要内容是核反应与核安全，老师上课不太清晰，且上课节奏很慢。会以低频次的提问代替考勤，不过也不太看重这个。有两次作业，一次是核反应的小计算，一次是核安全的分析思路。
最后课程报告为核安全事故分析，可以是福岛或者切尔诺贝利或者其他的，汇报无特别具体的要求，三四页word即可。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2026-01" }

[[courses]]
name = "现代电机设计导论"

[[courses.sections]]
title = "课程概况"

[[courses.sections.items]]
content = """
只有一次考勤，考勤方式是纸质名单签字，老师比较善良，无作业，无提问，无考试。
实验是4学时，我们安排在了周五7,8,9,10节，实际操作7,8节就可以搞定，报告很简单，好课推荐。
"""
author = { name = "jiazero", link = "https://github.com/jiazero", date = "2025-12" }
